[[entries]]
name = "nvim"
source_path = "nvim"
local_path = ".config/nvim"

[[entries]]
name = "ghostty"
source_path = "ghostty"
local_path = ".config/ghosty"

[[entries]]
name = "zsh"
source_path = "zsh/.zshrc"
local_path = ".zshrc"

[[entries]]
name = "starship"
source_path = "starship/starship.toml"
local_path = ".config/starship.toml"
